TFP-3795: Gui for å kunne sende inn delvis refusjon
navikt/fp-frontend pull request #327
Opened 2020-10-23 06:51 UTC by pekern

2020-11-10 13:47 UTC, pekern commented
Ser en test feiler, skal se på denne :)

2020-11-10 18:33 UTC, espenjv requested changes

2020-11-10 18:33 UTC, espenjv commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
> +  return `${prefix}${andel.arbeidsgiverId.arbeidsgiverAktørId}${andel.internArbeidsforholdRef}`;
Skal dette vere `andel.arbeidsgiver.arbeidsgiverAktørId`?

2020-11-10 18:33 UTC, espenjv commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
>    if (andel.arbeidsgiverId.arbeidsgiverOrgnr) {
Skal dette vere `andel.arbeidsgiver.arbeidsgiverOrgnr`?

2020-11-10 18:33 UTC, espenjv commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
> +              isEdited={!!refusjonAndel.fastsattDelvisRefusjonPrMnd}
Burde vi her sjekke om aksjonspunktet er løst i tillegg? Eg tenkjer på situasjonen der vi preutfyller/gjenoppretter bekreftet grunnlag ved tilbakehopp eller revurdering. Då vil vel dette feltet vere satt før vi har løst aksjonspunktet.

2020-11-10 18:33 UTC, espenjv commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
>    if (andel.arbeidsgiverId.arbeidsgiverOrgnr) {
Eg ser dette er gjort fleire ganger.

2020-11-11 06:46 UTC, pekern commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
> +  return `${prefix}${andel.arbeidsgiverId.arbeidsgiverAktørId}${andel.internArbeidsforholdRef}`;
Nei

2020-11-11 06:46 UTC, pekern commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
>    if (andel.arbeidsgiverId.arbeidsgiverOrgnr) {
Nei, det skal være andel.arbeidsgiverId.arbeidsgiverOrgnr

2020-11-11 10:15 UTC, espenjv commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
>    if (andel.arbeidsgiverId.arbeidsgiverOrgnr) {
Men RefusjonAndel.java har ikkje eit felt arbeidsgiverId.

2020-11-11 10:15 UTC, espenjv commented on packages/fakta-fordel-beregningsgrunnlag/src/components/refusjon/VurderEndringRefusjonRad.jsx
>    if (andel.arbeidsgiverId.arbeidsgiverOrgnr) {
Eg ser at det er RefusjonAndelTilVurderingDto som er brukt her. Litt forvirrende at den heiter refusjonAndel i komponenten. Eg synes forsåvidt at det er merkelig å kalle feltet arbeidsgiverId sidan klassen heiter Arbeidsgiver og den heiter arbeidsgiver alle andre stader.

2020-11-11 10:16 UTC, espenjv approved these changes
Godkjenner, men med oppfordring om å endre arbeidsgiverId til arbeidsgiver for konsistens.

2020-11-11 11:24 UTC, merged