TFP-3992 Mulighet for å legge til dagpengeandel ved overstyring +  fj…
navikt/fp-frontend pull request #622
Opened 2021-01-04 13:09 UTC by espenjv

…erning av MS om valgt til nei

2021-01-04 15:27 UTC, pekern requested changes

2021-01-04 15:27 UTC, pekern commented on packages/fakta-beregning/src/components/fellesFaktaForATFLogSN/AddDagpengerAndelButton.tsx
> +  andel: aktivitetStatuser.filter(({ kode }) => kode === aktivitetStatus.DAGPENGER)[0].navn,
om du bruker find istedenfor filter får du første match og slipper kalle [0]

2021-01-04 15:27 UTC, pekern commented on packages/fakta-beregning/src/components/fellesFaktaForATFLogSN/InntektFieldArray.tsx
> +  andel: aktivitetStatuser.filter(({ kode }) => kode === aktivitetStatus.MILITAER_ELLER_SIVIL)[0].navn,
Samme her med find istedenfor filter

2021-01-04 15:27 UTC, pekern commented on packages/fakta-beregning/src/components/fellesFaktaForATFLogSN/InntektFieldArray.tsx
> +  skalFjerne: (AndelFieldValue) => boolean,
AndelFieldValue er vel et parameternavn, eller mener du typen ved samme navn?

2021-01-05 06:11 UTC, espenjv commented on packages/fakta-beregning/src/components/fellesFaktaForATFLogSN/InntektFieldArray.tsx
> +  skalFjerne: (AndelFieldValue) => boolean,
Eg meiner typen.

2021-01-05 11:09 UTC, pekern approved these changes

2021-01-05 11:38 UTC, merged